version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-28-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout:

    - restore_cache:
        key: jars-{{ checksum "Droidcon-Boston/build.gradle" }}-{{ checksum  "Droidcon-Boston/app/build.gradle" }}

    - run:
       name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
       command: cd Droidcon-Boston && pwd && ls && sudo chmod +x ./gradlew

    - run:
        name: Download Dependencies
        command: cd Droidcon-Boston && ./gradlew androidDependencies

    - save_cache:
        paths:
        - .gradle
        key: jars-{{ checksum "Droidcon-Boston/build.gradle" }}-{{ checksum  "Droidcon-Boston/app/build.gradle" }}

    - run:
        name: Static Analysis Checks
        command: cd Droidcon-Boston && ./gradlew detekt ktlintCheck lint

    - run:
        name: Run Tests
        command: cd Droidcon-Boston && ./gradlew test

    - run:
        name: Assemble APK
        command: cd Droidcon-Boston && ./gradlew assembleRelease

    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: Droidcon-Boston/app/build/reports
        destination: reports

    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: Droidcon-Boston/app/build/outputs
        destination: outputs

    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: Droidcon-Boston/app/build/test-results
